import { createMiddleware } from '@solidjs/start/middleware';
import { normalizeTrailingSlash } from './lib/middleware/trailing-slash';
import { detectLocale } from './lib/middleware/locale-detection';
import { INLINE_SCRIPT_HASHES } from './generated/csp-hashes';

/**
 * SolidStart middleware orchestrator. Ports the edge-layer handlers
 * previously implemented in `src/worker.ts` into SolidStart's
 * `createMiddleware` pipeline so that the SolidStart deploy target
 * (Cloudflare Module Worker via `cloudflare-module` preset) can reuse
 * the same contract.
 *
 * Pipeline (onRequest, evaluated in declaration order; first handler
 * that returns a Response short-circuits downstream handlers and the
 * route handler itself):
 *
 *   1. Legacy admin alias: `/admin` + `/admin/*` -> 301 `/console[...]`
 *      (WP20 compat — preserves search string, permanent so caches
 *      absorb the redirect).
 *   2. CSP report sink: POST `/csp-report` -> 204 No Content. Body is
 *      intentionally discarded at this layer; the cloud-native log
 *      pipeline (wrangler tail / Cloudflare Logs) captures payloads.
 *   3. Root redirect: `/` -> 302 `/{detectLocale(Accept-Language)}/`.
 *      302 (not 301) so negotiated locale is not cached permanently
 *      against a UA that later changes language preferences.
 *   4. Trailing-slash / casing normalization via the pure helper in
 *      `lib/middleware/trailing-slash.ts`.
 *
 * onBeforeResponse:
 *   - Stamps `Content-Security-Policy` on text/html responses, built
 *     from the precomputed inline-script-hash whitelist. This lives in
 *     the Worker (not in `_headers`) because Cloudflare rejects header
 *     lines > 2000 char and the full directive with 79 hashes is
 *     ~4700 char. See TASK-W18-T31.
 *   - Stamps `X-Robots-Tag: noindex, nofollow` and `Cache-Control:
 *     no-store` on sensitive paths (checkout funnel, console admin UI,
 *     auth callback).
 */

const NOINDEX_PATTERNS: readonly RegExp[] = [
  /^\/[^/]+\/checkout(\/|$)/,       // /{lang}/checkout or /{lang}/checkout/*
  /^\/console(\/|$)/,                // /console or /console/*
  /^\/console-login\/?$/,            // /console-login
  /^\/auth\/google\/callback\/?$/,   // /auth/google/callback
];

function isNoindex(pathname: string): boolean {
  return NOINDEX_PATTERNS.some((re) => re.test(pathname));
}

/**
 * Build the full `Content-Security-Policy` directive with the baked-in
 * inline-script hashes. Precomputed at module load (cold start) so each
 * request pays only a Map.set cost (~microseconds) instead of rebuilding
 * the string.
 *
 * Mirror of the legacy static directive from `public/_headers` pre-WP18,
 * with two additions kept intentional:
 *   - `'strict-dynamic'` remains so a root-loaded bootstrap script can
 *     import further modules without listing each hash.
 *   - Cloudflare Insights script origin stays whitelisted for RUM.
 */
function buildCspHeader(): string {
  const scriptSrcTokens = [
    "'self'",
    ...INLINE_SCRIPT_HASHES.map((h) => `'${h}'`),
    "'strict-dynamic'",
    'https://static.cloudflareinsights.com',
  ];

  return [
    "default-src 'self'",
    `script-src ${scriptSrcTokens.join(' ')}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: https:",
    "font-src 'self' data:",
    "connect-src 'self' https://api.lolsensei.com https://api-beta.lolsensei.com https://static.cloudflareinsights.com https://cloudflareinsights.com",
    "frame-src 'none'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self' https://api.lolsensei.com",
    // WP24 M4 — ``report-to`` e' il successore di ``report-uri`` (deprecato).
    // Entrambi emessi per compat: browser legacy usano report-uri, i moderni
    // preferiscono report-to e il Reporting-API group ``csp-endpoint``.
    "report-uri /csp-report",
    "report-to csp-endpoint",
  ].join('; ');
}

// Module-level precomputed CSP header. Safe because INLINE_SCRIPT_HASHES is
// frozen at build time (generated by `scripts/compute-csp-hashes.mjs`).
const CSP_HEADER = buildCspHeader();

// WP24 TASK-4-022 — Report-Only mode toggle.
// When `CSP_REPORT_ONLY=true` at build time, the middleware emits the
// directive as `Content-Security-Policy-Report-Only` instead of the
// enforce header. Deploy workflow:
//   1. Enable Report-Only for 48h on preview/prod.
//   2. Monitor /csp-report endpoint for violations (MN-06: ignore
//      blocked-uri data:/inline — only flag external origins).
//   3. If 0 critical violations -> remove flag, deploy enforce.
// See docs/runbook-csp-report-only.md.
const CSP_REPORT_ONLY = (
  (import.meta.env.VITE_CSP_REPORT_ONLY as string | undefined) ?? 'false'
).toLowerCase() === 'true';
const CSP_HEADER_NAME = CSP_REPORT_ONLY
  ? 'Content-Security-Policy-Report-Only'
  : 'Content-Security-Policy';

export default createMiddleware({
  onRequest: [
    // 1. Legacy /admin/* -> 301 /console/*
    (event) => {
      const url = new URL(event.request.url);
      if (url.pathname === '/admin' || url.pathname.startsWith('/admin/')) {
        const target = url.pathname.replace(/^\/admin/, '/console') + url.search;
        return Response.redirect(new URL(target, url).toString(), 301);
      }
    },
    // 2. CSP report endpoint
    (event) => {
      const url = new URL(event.request.url);
      if (url.pathname === '/csp-report' && event.request.method === 'POST') {
        return new Response(null, { status: 204 });
      }
    },
    // 3. Root redirect -> /{detected-locale}/ (preserves query string so
    //    campaign/referral params survive the negotiated-locale hop).
    (event) => {
      const url = new URL(event.request.url);
      if (url.pathname === '/') {
        const locale = detectLocale(event.request.headers.get('accept-language'));
        const target = `/${locale}/${url.search}`;
        return Response.redirect(new URL(target, url).toString(), 302);
      }
    },
    // 4. Trailing-slash / casing normalization
    (event) => {
      const url = new URL(event.request.url);
      const intent = normalizeTrailingSlash(url, event.request.method);
      if (intent) {
        return new Response(null, {
          status: intent.status,
          headers: {
            Location: intent.location,
            'Cache-Control': 'public, max-age=3600',
          },
        });
      }
    },
  ],
  onBeforeResponse: [
    (event) => {
      // CSP: only on HTML responses. Assets (js/css/img/font) don't need it
      // and stamping CSP on them just inflates egress.
      const contentType = event.response.headers.get('content-type') || '';
      if (contentType.includes('text/html')) {
        event.response.headers.set(CSP_HEADER_NAME, CSP_HEADER);

        // WP24 M4 (SEC#7) + R2-MAJ-03 — hardening cross-origin isolation.
        // COOP ``same-origin`` mitiga Spectre-style cross-origin leaks.
        // COEP ``credentialless`` (invece di ``require-corp``): le risorse
        // cross-origin senza credenziali sono accettate senza bisogno di
        // ``Cross-Origin-Resource-Policy`` esplicito dall'origine remota.
        // Questo e' necessario per il beacon CF Web Analytics
        // (``static.cloudflareinsights.com/beacon.min.js``) caricato con
        // ``crossorigin="anonymous"`` — con ``require-corp`` veniva
        // potenzialmente bloccato se CF non emetteva CORP. Tradeoff:
        // ``credentialless`` rilassa leggermente la protezione Spectre
        // ma resta compatibile con il threat model LoL Sensei (no iframe
        // cross-origin, script CF stateless).
        event.response.headers.set('Cross-Origin-Opener-Policy', 'same-origin');
        event.response.headers.set('Cross-Origin-Resource-Policy', 'same-origin');
        event.response.headers.set('Cross-Origin-Embedder-Policy', 'credentialless');
        // Reporting-API endpoint group referenziato da ``report-to`` nella CSP.
        event.response.headers.set(
          'Reporting-Endpoints',
          'csp-endpoint="/csp-report"'
        );
      }

      // NOINDEX + Cache-Control: sensitive paths (checkout/console/auth).
      const url = new URL(event.request.url);
      if (isNoindex(url.pathname)) {
        event.response.headers.set('X-Robots-Tag', 'noindex, nofollow');
        event.response.headers.set('Cache-Control', 'no-store');
      }
    },
  ],
});
